---
repos:
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: /workspaces/app/.venv/bin/yamllint
        language: system
        types: [python]
        files: ^.*\.(yml|yaml)$

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: /workspaces/app/.venv/bin/pyright
        language: system
        types: [python]
        files: ^.*\.py$

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: /workspaces/app/.venv/bin/pylint
        language: system
        types: [python]
        files: ^.*\.py$

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: /workspaces/app/.venv/bin/flake8
        language: system
        types: [python]
        files: ^.*\.py$

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: /workspaces/app/.venv/bin/mypy
        language: system
        types: [python]
        files: ^.*\.py$

  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: /workspaces/app/.venv/bin/yapf
        language: system
        types: [python]
        files: ^.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main]

